"use strict";
// let a = Math.abs(7.25);
// let b = Math.abs(-7.25);
// //let c = Math.abs(null);
// //let d = Math.abs("Hello");
// let e = Math.abs(2 - 3);
// let a = Math.ceil(0.6);
// let b = Math.ceil(0.4);
// let c = Math.ceil(5);
// let d = Math.ceil(5.1);
// let e = Math.ceil(-5.1);
// let f = Math.ceil(-5.9);
let a = Math.round(2.6);
let b = Math.round(2.5);
let c = Math.round(2.49);
let d = Math.round(-2.6);
let e = Math.round(-2.5);
let f = Math.round(-2.49);
let x = Math.trunc(8.76);
let y = Math.trunc(8.3);
console.log(x);
console.log(y);
// console.log(a);
// console.log(b);
// console.log(c);
// console.log(d);
// console.log(e);
// console.log(f);
